name: eeztour
description: "A new Flutter project."
 
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: ^3.7.2


#..................packages............................#
dependencies:
  flutter:
    sdk: flutter
  # google_places_flutter: ^2.0.4
  google_places_flutter: ^2.0.4
  intl: ^0.20.2

  provider: ^6.0.3
  http: ^0.13.5 
  fl_chart: ^0.64.0

  
  #Meraj
  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.5.0
  google_maps_webservice: ^0.0.19
  flutter_dotenv: ^5.1.0
  google_place: ^0.4.7
  flutter_svg: ^2.0.9
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.2.0
#  share_plus: ^11.0.0
#  url_launcher: ^6.2.5
  clipboard: ^0.1.3






#utility


#Icons  
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

#state management


#product specific
  get: ^4.6.5

#...................... ./ packages end..................#





dev_dependencies:
  flutter_test:
    sdk: flutter
   
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

   
#.................. LOCAL ASSETS ............................#

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/images/calendar_icon.png
    - assets/icons/enter.svg
    - .env

#.................. LOCAL FONTS ............................#
 
  # fonts:
  #   -  family:

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
